/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * ASP.NET-10
 *
 * Domain Model:
 * Healthcare Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace healthcareonaspdotnet.Domain;

/// <summary>
/// TaskStatus enumerator class
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]

public enum TaskStatus
{
    Requested=1,Accepted=2,InProgress=3,Completed=4,Cancelled=5,Failed=6
}

/// <summary>
/// Extension of capabilities for the TaskStatus enum
/// </summary>
public static class TaskStatusExtensions
{
    //************************************************************************
    // static implementations
    //************************************************************************
    public static List<TaskStatus> GetValues()
    {
        return Enum.GetValues<TaskStatus>().ToList();
    }

    public static TaskStatus GetDefaultValue()
    {
        return Enum.GetValues<TaskStatus>().First();
    }

    public static TaskStatus WhichOne(string name)
    {
        if (Enum.TryParse<TaskStatus>(name, true, out var value))
        {
            return value;
        }

        return GetDefaultValue();
    }
}



